
  
build_test:
  script:
    - curl -LO https://dl.google.com/go/go1.13.12.linux-amd64.tar.gz
    - tar zxf go1.13.12.linux-amd64.tar.gz
    - export GOPATH=$HOME/go
    - export PATH=$GOPATH/bin:$PATH
    - export LDFLAGS="-X main.gitCommit=$(git rev-parse --short HEAD) -X main.gitBranch=$(git rev-parse --abbrev-ref HEAD)"
    - go install -ldflags "$LDFLAGS"
  
deploy:
  only:
    refs:
       - master
  script:
    - git checkout master
    - go build -ldflags "$LDFLAGS" -o sftp_downloader
    - aws s3 cp sftp_downloader s3://$AWS_S3_BUCKET/sftp_downloader/ --acl public-read
  
