
  
build_test:
  script:
    - curl -LO https://dl.google.com/go/go1.13.12.linux-amd64.tar.gz
    - tar zxf go1.13.12.linux-amd64.tar.gz
    - export PATH=:$(pwd)/go/bin:$PATH
    - export GOPATH=$(pwd)/go
    - GO111MODULE=on go get github.com/golang/mock/mockgen@latest
    - ./build.sh
  
deploy:
  only:
    refs:
       - master
  script:
    - aws s3 cp builds/sftp_downloader_linux s3://$AWS_S3_BUCKET/sftp_downloader/ --acl public-read
  
