defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/golang:1.9.2

version: 2
jobs:
  flow:
    <<: *defaults
    working_directory: /go/src/github.com/FredHutch/sftp_downloader
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/golang/mock/gomock
      - run: go get github.com/golang/mock/mockgen
      - run: mkdir -p builds mocks
      - run: go generate ./...
      - run: go test -coverprofile=coverage.out -v
      - run: go tool cover -func=coverage.out
      - run: go build -o builds/sftp_downloader -ldflags "-X main.gitCommit=$(git rev-parse --short HEAD) -X main.gitBranch=$(git rev-parse --abbrev-ref HEAD)"

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: builds
          # Must be relative path from root
          paths:
            - sftp_downloader

  downstream:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run: curl -O https://bootstrap.pypa.io/get-pip.py
      - run: python get-pip.py --user
      - run: ~/.local/bin/pip install awscli --upgrade --user
      - run: ~/.local/bin/aws s3 cp /tmp/workspace/sftp_downloader s3://fredhutch-scicomp-tools/sftp_downloader/sftp_downloader --acl public-read

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
          filters:
            branches:
              only: master
