name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    # - name: Get dependencies
    #   run: |
    #     mkdir -p /home/runner/go/bin
    #     go get -v -t -d ./...
    #     if [ -f Gopkg.toml ]; then
    #         curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    #         /home/runner/go/bin/dep ensure
    #     fi

    - name: Build
      env:
        LDFLAGS: "-X main.gitCommit=$(git rev-parse --short HEAD) -X main.gitBranch=$(git rev-parse --abbrev-ref HEAD)"
        PATH: "$PATH:$GOPATH:/bin"
      run:  |
        git branch
        go install -ldflags "$LDFLAGS"
        GOOS=linux   GOARCH=amd64 go build -ldflags "$LDFLAGS" -o sftp_downloader
      
    - name: Upload binary to S3 bucket
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        FILE: ./sftp_downloader
        AWS_REGION: 'us-west-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
